
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <stdexcept>
#include <utility>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>
#include <openassetio/trait/property.hpp>

namespace openassetio_abi = openassetio::v1;

namespace openassetio_mediacreation {
inline namespace v1 {
namespace traits::auth {

namespace property = openassetio_abi::trait::property;

/**
 * This trait holds an authentication token that the manager may pass to
 * a back-end service.
 * Usage: locale
 */
class BearerTokenTrait {
public:
  static inline const openassetio_abi::trait::TraitId kId = "openassetio-mediacreation:auth.BearerToken";

  /**
   * Construct this trait view, wrapping the given TraitsData instance.
   */
  explicit BearerTokenTrait(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Check whether a TraitsData instance has this trait set.
   *
   * @param traitsData Data to check.
   * @return `true` if the given TraitsData instance has this trait
   * set, `false` otherwise.
   */
  [[nodiscard]] static bool isImbuedTo(const openassetio::TraitsDataPtr& traitsData) {
    return traitsData->hasTrait(kId);
  }

  /**
   * Check whether the TraitsData instance this trait has been
   * constructed with has this trait set.
   *
   * @return `true` if the underlying TraitsData instance has this trait
   * set, `false` otherwise.
   **/
  [[nodiscard]] bool isImbued() const { return isImbuedTo(traitsData_); }

  /**
   * Applies this trait to the wrapped TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   **/
  void imbue() const { imbueTo(traitsData_); }

  /**
   * Applies this trait to the supplied TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   *
   * @param traitsData The instance to apply the trait to.
   **/
  static void imbueTo(const openassetio::TraitsDataPtr& traitsData) { traitsData->addTrait(kId); }

  /**
   * Sets the token property.
   *
   * Contents of the token.
   */
  void setToken(openassetio::Str token) {
    traitsData_->setTraitProperty(kId, property::Key{"token"}, std::move(token));
  }

  /**
   * Gets the value of the token property or the supplied
   * default.
   *
   * Contents of the token.
   */
  [[nodiscard]] openassetio::Str getToken(const openassetio::Str& defaultValue) const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "token")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
    }
    return defaultValue;
  }

  /**
   * Gets the value of the token property or throws if
   * not found or is of an unexpected type.
   *
   * Contents of the token.
   */
  [[nodiscard]] openassetio::Str getToken() const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "token")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
      throw std::runtime_error{"Invalid stored value type: should be 'openassetio::Str'."};
    }
    throw std::runtime_error{"Property is not set."};
  }

private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace traits::auth
}  // namespace v1
}  // namespace openassetio_mediacreation