
#ifndef OPENASSETIO_PYTHON_BRIDGE_EXPORT_H
#define OPENASSETIO_PYTHON_BRIDGE_EXPORT_H

#ifdef OPENASSETIO_PYTHON_BRIDGE_STATIC_DEFINE
#  define OPENASSETIO_PYTHON_BRIDGE_EXPORT
#  define OPENASSETIO_PYTHON_BRIDGE_NO_EXPORT
#else
#  ifndef OPENASSETIO_PYTHON_BRIDGE_EXPORT
#    ifdef openassetio_python_bridge_EXPORTS
        /* We are building this library */
#      define OPENASSETIO_PYTHON_BRIDGE_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define OPENASSETIO_PYTHON_BRIDGE_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef OPENASSETIO_PYTHON_BRIDGE_NO_EXPORT
#    define OPENASSETIO_PYTHON_BRIDGE_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef OPENASSETIO_PYTHON_BRIDGE_DEPRECATED
#  define OPENASSETIO_PYTHON_BRIDGE_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef OPENASSETIO_PYTHON_BRIDGE_DEPRECATED_EXPORT
#  define OPENASSETIO_PYTHON_BRIDGE_DEPRECATED_EXPORT OPENASSETIO_PYTHON_BRIDGE_EXPORT OPENASSETIO_PYTHON_BRIDGE_DEPRECATED
#endif

#ifndef OPENASSETIO_PYTHON_BRIDGE_DEPRECATED_NO_EXPORT
#  define OPENASSETIO_PYTHON_BRIDGE_DEPRECATED_NO_EXPORT OPENASSETIO_PYTHON_BRIDGE_NO_EXPORT OPENASSETIO_PYTHON_BRIDGE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef OPENASSETIO_PYTHON_BRIDGE_NO_DEPRECATED
#    define OPENASSETIO_PYTHON_BRIDGE_NO_DEPRECATED
#  endif
#endif

#endif /* OPENASSETIO_PYTHON_BRIDGE_EXPORT_H */
