
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <stdexcept>
#include <utility>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>
#include <openassetio/trait/property.hpp>

namespace openassetio_abi = openassetio::v1;

namespace openassetio_mediacreation {
inline namespace v1 {
namespace traits::lifecycle {

namespace property = openassetio_abi::trait::property;

/**
 * Defines that the entity references returned from a relationship query
 * with this trait should be devoid of any dynamic behaviour. This
 * includes concepts such as meta-versioning or context-specific
 * variation that results logically different data being supplied.
 * 
 * This is generally used to snapshot/bookmark specific configurations
 * to avoid temporal instability and/or ensure processes are repeatable.
 * 
 * Note: This does not include variations such as regional adaptation of
 * the LocatableContent trait, where the underlying data remains the
 * same.
 * Usage: relationship
 */
class StableTrait {
public:
  static inline const openassetio_abi::trait::TraitId kId = "openassetio-mediacreation:lifecycle.Stable";

  /**
   * Construct this trait view, wrapping the given TraitsData instance.
   */
  explicit StableTrait(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Check whether a TraitsData instance has this trait set.
   *
   * @param traitsData Data to check.
   * @return `true` if the given TraitsData instance has this trait
   * set, `false` otherwise.
   */
  [[nodiscard]] static bool isImbuedTo(const openassetio::TraitsDataPtr& traitsData) {
    return traitsData->hasTrait(kId);
  }

  /**
   * Check whether the TraitsData instance this trait has been
   * constructed with has this trait set.
   *
   * @return `true` if the underlying TraitsData instance has this trait
   * set, `false` otherwise.
   **/
  [[nodiscard]] bool isImbued() const { return isImbuedTo(traitsData_); }

  /**
   * Applies this trait to the wrapped TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   **/
  void imbue() const { imbueTo(traitsData_); }

  /**
   * Applies this trait to the supplied TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   *
   * @param traitsData The instance to apply the trait to.
   **/
  static void imbueTo(const openassetio::TraitsDataPtr& traitsData) { traitsData->addTrait(kId); }

private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace traits::lifecycle
}  // namespace v1
}  // namespace openassetio_mediacreation