
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <stdexcept>
#include <utility>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>
#include <openassetio/trait/property.hpp>

namespace openassetio_abi = openassetio::v1;

namespace openassetio_mediacreation {
inline namespace v1 {
namespace traits::lifecycle {

namespace property = openassetio_abi::trait::property;

/**
 * Describes a specific version of an entity.
 * 
 * A version is defined as a revision or iteration of what is otherwise
 * the same logical entity. If supported by a manager, versions are
 * created when new data is published to an existing entity. Not all
 * managers may version all types of entity.
 * 
 * There is no requirement for version to be a singular atomic series,
 * managers may wish to support "meta versions", such as 'vLatest' or
 * similar, or provide multiple parallel versioning streams.
 * 
 * This trait can be used in several places:
 *  - When resolved, the manager should provide information about
 *    the version of the referenced entity. This trait should only
 *    be imbued if the target entity is considered versioned by the
 *    manager, and it can populate the stableTag property.
 *  - When responding to managementPolicy for an entity trait set,
 *    the manager should imbue this trait if that type of entity
 *    is version managed by the manager (not all managers version
 *    all types of entity).
 *  - When used within a relationship query, this trait indicates
 *    that the returned entities should be constrained to other
 *    versions of the logical entity targeted by the reference.
 * Usage: entity, relationship, managementPolicy
 */
class VersionTrait {
public:
  static inline const openassetio_abi::trait::TraitId kId = "openassetio-mediacreation:lifecycle.Version";

  /**
   * Construct this trait view, wrapping the given TraitsData instance.
   */
  explicit VersionTrait(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Check whether a TraitsData instance has this trait set.
   *
   * @param traitsData Data to check.
   * @return `true` if the given TraitsData instance has this trait
   * set, `false` otherwise.
   */
  [[nodiscard]] static bool isImbuedTo(const openassetio::TraitsDataPtr& traitsData) {
    return traitsData->hasTrait(kId);
  }

  /**
   * Check whether the TraitsData instance this trait has been
   * constructed with has this trait set.
   *
   * @return `true` if the underlying TraitsData instance has this trait
   * set, `false` otherwise.
   **/
  [[nodiscard]] bool isImbued() const { return isImbuedTo(traitsData_); }

  /**
   * Applies this trait to the wrapped TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   **/
  void imbue() const { imbueTo(traitsData_); }

  /**
   * Applies this trait to the supplied TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   *
   * @param traitsData The instance to apply the trait to.
   **/
  static void imbueTo(const openassetio::TraitsDataPtr& traitsData) { traitsData->addTrait(kId); }

  /**
   * Sets the specifiedTag property.
   *
   * An unambiguous identifier (tag) for the specific version of  an
     * entity targeted by a specific reference.
     * 
     * Examples of version tags include "1", "v2", "latest".
     * 
     * If the reference itself does not contain a version specifier and
     * relies on dynamic behaviour, then this should be left empty.
   */
  void setSpecifiedTag(openassetio::Str specifiedTag) {
    traitsData_->setTraitProperty(kId, property::Key{"specifiedTag"}, std::move(specifiedTag));
  }

  /**
   * Gets the value of the specifiedTag property or the supplied
   * default.
   *
   * An unambiguous identifier (tag) for the specific version of  an
    * entity targeted by a specific reference.
    * 
    * Examples of version tags include "1", "v2", "latest".
    * 
    * If the reference itself does not contain a version specifier and
    * relies on dynamic behaviour, then this should be left empty.
   */
  [[nodiscard]] openassetio::Str getSpecifiedTag(const openassetio::Str& defaultValue) const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "specifiedTag")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
    }
    return defaultValue;
  }

  /**
   * Gets the value of the specifiedTag property or throws if
   * not found or is of an unexpected type.
   *
   * An unambiguous identifier (tag) for the specific version of  an
    * entity targeted by a specific reference.
    * 
    * Examples of version tags include "1", "v2", "latest".
    * 
    * If the reference itself does not contain a version specifier and
    * relies on dynamic behaviour, then this should be left empty.
   */
  [[nodiscard]] openassetio::Str getSpecifiedTag() const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "specifiedTag")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
      throw std::runtime_error{"Invalid stored value type: should be 'openassetio::Str'."};
    }
    throw std::runtime_error{"Property is not set."};
  }

  /**
   * Sets the stableTag property.
   *
   * The tag (see 'specifiedTag') targeted by the reference once meta-
     * versions or other dynamic behaviour is applied.
     * 
     * If, for example, references without an explicit version yield the
     * most recent, then this should be set to the tag of that version. When
     * referencing some other semantic state (eg. approval), this should be
     * set to the tag of the concrete version that matches the specific
     * state.
     * 
     * Examples of stable version tags include "1", "v2".
     * 
     * This property should always be set when the Version trait is imbued
     * as part of a resolve response. If the entity is not versioned, then
     * the trait itself should not be imbued.
   */
  void setStableTag(openassetio::Str stableTag) {
    traitsData_->setTraitProperty(kId, property::Key{"stableTag"}, std::move(stableTag));
  }

  /**
   * Gets the value of the stableTag property or the supplied
   * default.
   *
   * The tag (see 'specifiedTag') targeted by the reference once meta-
    * versions or other dynamic behaviour is applied.
    * 
    * If, for example, references without an explicit version yield the
    * most recent, then this should be set to the tag of that version. When
    * referencing some other semantic state (eg. approval), this should be
    * set to the tag of the concrete version that matches the specific
    * state.
    * 
    * Examples of stable version tags include "1", "v2".
    * 
    * This property should always be set when the Version trait is imbued
    * as part of a resolve response. If the entity is not versioned, then
    * the trait itself should not be imbued.
   */
  [[nodiscard]] openassetio::Str getStableTag(const openassetio::Str& defaultValue) const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "stableTag")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
    }
    return defaultValue;
  }

  /**
   * Gets the value of the stableTag property or throws if
   * not found or is of an unexpected type.
   *
   * The tag (see 'specifiedTag') targeted by the reference once meta-
    * versions or other dynamic behaviour is applied.
    * 
    * If, for example, references without an explicit version yield the
    * most recent, then this should be set to the tag of that version. When
    * referencing some other semantic state (eg. approval), this should be
    * set to the tag of the concrete version that matches the specific
    * state.
    * 
    * Examples of stable version tags include "1", "v2".
    * 
    * This property should always be set when the Version trait is imbued
    * as part of a resolve response. If the entity is not versioned, then
    * the trait itself should not be imbued.
   */
  [[nodiscard]] openassetio::Str getStableTag() const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "stableTag")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
      throw std::runtime_error{"Invalid stored value type: should be 'openassetio::Str'."};
    }
    throw std::runtime_error{"Property is not set."};
  }

private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace traits::lifecycle
}  // namespace v1
}  // namespace openassetio_mediacreation