
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <stdexcept>
#include <utility>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>
#include <openassetio/trait/property.hpp>

namespace openassetio_abi = openassetio::v1;

namespace openassetio_mediacreation {
inline namespace v1 {
namespace traits::managementPolicy {

namespace property = openassetio_abi::trait::property;

/**
 * A trait indicating that the data matching the supplied trait set is
 * handled by the manager.
 * 
 * There are three possible policies determined by applying/querying
 * this trait: * If the response is not imbued with this trait, then the
 *   Manager has no interest in participating in the management of
 *   entities that match the queried trait set, for either read or
 *   write.
 * * If the response is imbued with this trait, but the "exclusive"
 *   property is not set, or set to False, then the Manager would
 *     like the opportunity to manage the data, but the user should
 *     still be presented with standard Host UI for the type as an
 *     option.
 *   * If the "exclusive" property is set to true, then the Manager
 *     takes exclusive control over data with the queried trait set,
 *     and any standard host interfaces etc should be suppressed.
 * Usage: managementPolicy
 */
class ManagedTrait {
public:
  static inline const openassetio_abi::trait::TraitId kId = "openassetio-mediacreation:managementPolicy.Managed";

  /**
   * Construct this trait view, wrapping the given TraitsData instance.
   */
  explicit ManagedTrait(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Check whether a TraitsData instance has this trait set.
   *
   * @param traitsData Data to check.
   * @return `true` if the given TraitsData instance has this trait
   * set, `false` otherwise.
   */
  [[nodiscard]] static bool isImbuedTo(const openassetio::TraitsDataPtr& traitsData) {
    return traitsData->hasTrait(kId);
  }

  /**
   * Check whether the TraitsData instance this trait has been
   * constructed with has this trait set.
   *
   * @return `true` if the underlying TraitsData instance has this trait
   * set, `false` otherwise.
   **/
  [[nodiscard]] bool isImbued() const { return isImbuedTo(traitsData_); }

  /**
   * Applies this trait to the wrapped TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   **/
  void imbue() const { imbueTo(traitsData_); }

  /**
   * Applies this trait to the supplied TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   *
   * @param traitsData The instance to apply the trait to.
   **/
  static void imbueTo(const openassetio::TraitsDataPtr& traitsData) { traitsData->addTrait(kId); }

  /**
   * Sets the exclusive property.
   *
   * Determines if the manager exclusively handles data matching the
     * supplied trait set.
     * 
     * If True, then standard host contols should be disabled in favour of
     * manager delegated UI. For example, file system browsers when
     * determining where to load/save data.
     * 
     * If False, then standard host controls can be presented in addition to
     * any custom manager UI.
   */
  void setExclusive(openassetio::Bool exclusive) {
    traitsData_->setTraitProperty(kId, property::Key{"exclusive"}, exclusive);
  }

  /**
   * Gets the value of the exclusive property or the supplied
   * default.
   *
   * Determines if the manager exclusively handles data matching the
    * supplied trait set.
    * 
    * If True, then standard host contols should be disabled in favour of
    * manager delegated UI. For example, file system browsers when
    * determining where to load/save data.
    * 
    * If False, then standard host controls can be presented in addition to
    * any custom manager UI.
   */
  [[nodiscard]] openassetio::Bool getExclusive(const openassetio::Bool& defaultValue) const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "exclusive")) {
      if (openassetio::Bool* maybeOut = std::get_if<openassetio::Bool>(&value)) {
        return *maybeOut;
      }
    }
    return defaultValue;
  }

  /**
   * Gets the value of the exclusive property or throws if
   * not found or is of an unexpected type.
   *
   * Determines if the manager exclusively handles data matching the
    * supplied trait set.
    * 
    * If True, then standard host contols should be disabled in favour of
    * manager delegated UI. For example, file system browsers when
    * determining where to load/save data.
    * 
    * If False, then standard host controls can be presented in addition to
    * any custom manager UI.
   */
  [[nodiscard]] openassetio::Bool getExclusive() const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "exclusive")) {
      if (openassetio::Bool* maybeOut = std::get_if<openassetio::Bool>(&value)) {
        return *maybeOut;
      }
      throw std::runtime_error{"Invalid stored value type: should be 'openassetio::Bool'."};
    }
    throw std::runtime_error{"Property is not set."};
  }

private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace traits::managementPolicy
}  // namespace v1
}  // namespace openassetio_mediacreation