
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <stdexcept>
#include <utility>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>
#include <openassetio/trait/property.hpp>

namespace openassetio_abi = openassetio::v1;

namespace openassetio_mediacreation {
inline namespace v1 {
namespace traits::managementPolicy {

namespace property = openassetio_abi::trait::property;

/**
 * A trait indicating a manager can potentially resolve the supplied
 * trait set for future entities.
 * 
 * If not imbued, the manager is not capable of determining data in
 * advance for new entities, and is only capable of resolving traits for
 * exising ones.
 * 
 * An example of this would be the ability to resolve a
 * LocatableContentTrait in advance, to determine where new data should
 * be written. When this trait imbued in the managementPolicy response,
 * a host may attempt to resolve the locatableContent trait of a working
 * entity reference supplied by preflight in order to determine a
 * suitable output path before work is done. In its absence, a host must
 * use alternate means to determine a suitable output location.
 * Usage: managementPolicy
 */
class ResolvesFutureEntitiesTrait {
public:
  static inline const openassetio_abi::trait::TraitId kId = "openassetio-mediacreation:managementPolicy.ResolvesFutureEntities";

  /**
   * Construct this trait view, wrapping the given TraitsData instance.
   */
  explicit ResolvesFutureEntitiesTrait(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Check whether a TraitsData instance has this trait set.
   *
   * @param traitsData Data to check.
   * @return `true` if the given TraitsData instance has this trait
   * set, `false` otherwise.
   */
  [[nodiscard]] static bool isImbuedTo(const openassetio::TraitsDataPtr& traitsData) {
    return traitsData->hasTrait(kId);
  }

  /**
   * Check whether the TraitsData instance this trait has been
   * constructed with has this trait set.
   *
   * @return `true` if the underlying TraitsData instance has this trait
   * set, `false` otherwise.
   **/
  [[nodiscard]] bool isImbued() const { return isImbuedTo(traitsData_); }

  /**
   * Applies this trait to the wrapped TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   **/
  void imbue() const { imbueTo(traitsData_); }

  /**
   * Applies this trait to the supplied TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   *
   * @param traitsData The instance to apply the trait to.
   **/
  static void imbueTo(const openassetio::TraitsDataPtr& traitsData) { traitsData->addTrait(kId); }

private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace traits::managementPolicy
}  // namespace v1
}  // namespace openassetio_mediacreation