
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <stdexcept>
#include <utility>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>
#include <openassetio/trait/property.hpp>

namespace openassetio_abi = openassetio::v1;

namespace openassetio_mediacreation {
inline namespace v1 {
namespace traits::content {

namespace property = openassetio_abi::trait::property;

/**
 * This trait characterizes an entity whose data is persisted externally
 * to the API through data accessible via a valid URL.
 * 
 * The `location` property holds the most applicable location of the
 * entity's content for the current process environment - considering
 * platform, host, etc. Location is in the form of a URL.
 * Usage: entity
 */
class LocatableContentTrait {
public:
  static inline const openassetio_abi::trait::TraitId kId = "openassetio-mediacreation:content.LocatableContent";

  /**
   * Construct this trait view, wrapping the given TraitsData instance.
   */
  explicit LocatableContentTrait(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Check whether a TraitsData instance has this trait set.
   *
   * @param traitsData Data to check.
   * @return `true` if the given TraitsData instance has this trait
   * set, `false` otherwise.
   */
  [[nodiscard]] static bool isImbuedTo(const openassetio::TraitsDataPtr& traitsData) {
    return traitsData->hasTrait(kId);
  }

  /**
   * Check whether the TraitsData instance this trait has been
   * constructed with has this trait set.
   *
   * @return `true` if the underlying TraitsData instance has this trait
   * set, `false` otherwise.
   **/
  [[nodiscard]] bool isImbued() const { return isImbuedTo(traitsData_); }

  /**
   * Applies this trait to the wrapped TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   **/
  void imbue() const { imbueTo(traitsData_); }

  /**
   * Applies this trait to the supplied TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   *
   * @param traitsData The instance to apply the trait to.
   **/
  static void imbueTo(const openassetio::TraitsDataPtr& traitsData) { traitsData->addTrait(kId); }

  /**
   * Sets the location property.
   *
   * The location of the entity's external content.
     * 
     * This must be a valid URL, so special characters need to be encoded
     * accordingly.
   */
  void setLocation(openassetio::Str location) {
    traitsData_->setTraitProperty(kId, property::Key{"location"}, std::move(location));
  }

  /**
   * Gets the value of the location property or the supplied
   * default.
   *
   * The location of the entity's external content.
    * 
    * This must be a valid URL, so special characters need to be encoded
    * accordingly.
   */
  [[nodiscard]] openassetio::Str getLocation(const openassetio::Str& defaultValue) const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "location")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
    }
    return defaultValue;
  }

  /**
   * Gets the value of the location property or throws if
   * not found or is of an unexpected type.
   *
   * The location of the entity's external content.
    * 
    * This must be a valid URL, so special characters need to be encoded
    * accordingly.
   */
  [[nodiscard]] openassetio::Str getLocation() const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "location")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
      throw std::runtime_error{"Invalid stored value type: should be 'openassetio::Str'."};
    }
    throw std::runtime_error{"Property is not set."};
  }

private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace traits::content
}  // namespace v1
}  // namespace openassetio_mediacreation