
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <stdexcept>
#include <utility>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>
#include <openassetio/trait/property.hpp>

namespace openassetio_abi = openassetio::v1;

namespace openassetio_mediacreation {
inline namespace v1 {
namespace traits::relationship {

namespace property = openassetio_abi::trait::property;

/**
 * The relationship should return at most one reference for each input.
 * Unless otherwise qualified, relationships are considered one-to-many.
 * Usage: relationship
 */
class SingularTrait {
public:
  static inline const openassetio_abi::trait::TraitId kId = "openassetio-mediacreation:relationship.Singular";

  /**
   * Construct this trait view, wrapping the given TraitsData instance.
   */
  explicit SingularTrait(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Check whether a TraitsData instance has this trait set.
   *
   * @param traitsData Data to check.
   * @return `true` if the given TraitsData instance has this trait
   * set, `false` otherwise.
   */
  [[nodiscard]] static bool isImbuedTo(const openassetio::TraitsDataPtr& traitsData) {
    return traitsData->hasTrait(kId);
  }

  /**
   * Check whether the TraitsData instance this trait has been
   * constructed with has this trait set.
   *
   * @return `true` if the underlying TraitsData instance has this trait
   * set, `false` otherwise.
   **/
  [[nodiscard]] bool isImbued() const { return isImbuedTo(traitsData_); }

  /**
   * Applies this trait to the wrapped TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   **/
  void imbue() const { imbueTo(traitsData_); }

  /**
   * Applies this trait to the supplied TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   *
   * @param traitsData The instance to apply the trait to.
   **/
  static void imbueTo(const openassetio::TraitsDataPtr& traitsData) { traitsData->addTrait(kId); }

private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace traits::relationship
}  // namespace v1
}  // namespace openassetio_mediacreation