
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <stdexcept>
#include <utility>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>
#include <openassetio/trait/property.hpp>

namespace openassetio_abi = openassetio::v1;

namespace openassetio_mediacreation {
inline namespace v1 {
namespace traits::identity {

namespace property = openassetio_abi::trait::property;

/**
 * Names that can be presented to a user in order to identify and/or
 * disambiguate the entity. These strings are potentially unstable and
 * should not be used as a UUID or other persistent anchor.
 * Usage: entity
 */
class DisplayNameTrait {
public:
  static inline const openassetio_abi::trait::TraitId kId = "openassetio-mediacreation:identity.DisplayName";

  /**
   * Construct this trait view, wrapping the given TraitsData instance.
   */
  explicit DisplayNameTrait(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Check whether a TraitsData instance has this trait set.
   *
   * @param traitsData Data to check.
   * @return `true` if the given TraitsData instance has this trait
   * set, `false` otherwise.
   */
  [[nodiscard]] static bool isImbuedTo(const openassetio::TraitsDataPtr& traitsData) {
    return traitsData->hasTrait(kId);
  }

  /**
   * Check whether the TraitsData instance this trait has been
   * constructed with has this trait set.
   *
   * @return `true` if the underlying TraitsData instance has this trait
   * set, `false` otherwise.
   **/
  [[nodiscard]] bool isImbued() const { return isImbuedTo(traitsData_); }

  /**
   * Applies this trait to the wrapped TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   **/
  void imbue() const { imbueTo(traitsData_); }

  /**
   * Applies this trait to the supplied TraitsData instance.
   *
   * If the instance already has this trait, it is a no-op.
   *
   * @param traitsData The instance to apply the trait to.
   **/
  static void imbueTo(const openassetio::TraitsDataPtr& traitsData) { traitsData->addTrait(kId); }

  /**
   * Sets the name property.
   *
   * The humanized name of entity itself, not including any hierarchy or
     * classification.
     * 
     * For example: - `"Cuttlefish v1"` - for a version of an asset -
     * `"seq003"` - for a sequence in a hierarchy
   */
  void setName(openassetio::Str name) {
    traitsData_->setTraitProperty(kId, property::Key{"name"}, std::move(name));
  }

  /**
   * Gets the value of the name property or the supplied
   * default.
   *
   * The humanized name of entity itself, not including any hierarchy or
    * classification.
    * 
    * For example: - `"Cuttlefish v1"` - for a version of an asset -
    * `"seq003"` - for a sequence in a hierarchy
   */
  [[nodiscard]] openassetio::Str getName(const openassetio::Str& defaultValue) const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "name")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
    }
    return defaultValue;
  }

  /**
   * Gets the value of the name property or throws if
   * not found or is of an unexpected type.
   *
   * The humanized name of entity itself, not including any hierarchy or
    * classification.
    * 
    * For example: - `"Cuttlefish v1"` - for a version of an asset -
    * `"seq003"` - for a sequence in a hierarchy
   */
  [[nodiscard]] openassetio::Str getName() const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "name")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
      throw std::runtime_error{"Invalid stored value type: should be 'openassetio::Str'."};
    }
    throw std::runtime_error{"Property is not set."};
  }

  /**
   * Sets the qualifiedName property.
   *
   * An unambiguous, humanized name for the entity.
     * 
     * The display name may want to consider the host, and any other
     * relevant Context information to form a display name for an entity
     * that can uniquely identify the entity in that context.
     * 
     * For example: - `"dive / build / cuttlefish / model / v1"` for a
     * version
     *     of an asset in an 'open recent' menu.
     * - `"Sequence 003 [ Dive / Episode 1 ]"` for a sequence in
     *    a hierarchy as a window title.
   */
  void setQualifiedName(openassetio::Str qualifiedName) {
    traitsData_->setTraitProperty(kId, property::Key{"qualifiedName"}, std::move(qualifiedName));
  }

  /**
   * Gets the value of the qualifiedName property or the supplied
   * default.
   *
   * An unambiguous, humanized name for the entity.
    * 
    * The display name may want to consider the host, and any other
    * relevant Context information to form a display name for an entity
    * that can uniquely identify the entity in that context.
    * 
    * For example: - `"dive / build / cuttlefish / model / v1"` for a
    * version
    *     of an asset in an 'open recent' menu.
    * - `"Sequence 003 [ Dive / Episode 1 ]"` for a sequence in
    *    a hierarchy as a window title.
   */
  [[nodiscard]] openassetio::Str getQualifiedName(const openassetio::Str& defaultValue) const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "qualifiedName")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
    }
    return defaultValue;
  }

  /**
   * Gets the value of the qualifiedName property or throws if
   * not found or is of an unexpected type.
   *
   * An unambiguous, humanized name for the entity.
    * 
    * The display name may want to consider the host, and any other
    * relevant Context information to form a display name for an entity
    * that can uniquely identify the entity in that context.
    * 
    * For example: - `"dive / build / cuttlefish / model / v1"` for a
    * version
    *     of an asset in an 'open recent' menu.
    * - `"Sequence 003 [ Dive / Episode 1 ]"` for a sequence in
    *    a hierarchy as a window title.
   */
  [[nodiscard]] openassetio::Str getQualifiedName() const {
    if (property::Value value; traitsData_->getTraitProperty(&value, kId, "qualifiedName")) {
      if (openassetio::Str* maybeOut = std::get_if<openassetio::Str>(&value)) {
        return *maybeOut;
      }
      throw std::runtime_error{"Invalid stored value type: should be 'openassetio::Str'."};
    }
    throw std::runtime_error{"Property is not set."};
  }

private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace traits::identity
}  // namespace v1
}  // namespace openassetio_mediacreation