
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once
/**
 * @namespace openassetio_mediacreation::v1::specifications::lifecycle
 *
 * Specification definitions in the 'lifecycle' namespace.
 *
 * Specifications that are concerned with describing aspects of the
 * lifecycle of an entity, such as versioning.
 */

#include "lifecycle/EntityVersionsRelationshipSpecification.hpp"
#include "lifecycle/StableEntityVersionsRelationshipSpecification.hpp"
#include "lifecycle/StableReferenceRelationshipSpecification.hpp"

