
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

/**
 * @namespace openassetio_mediacreation::v1::traits::auth
 *
 * Trait definitions in the 'auth' namespace.
 *
 * Traits related to authentication and authorization.
 */

#include "auth/BearerTokenTrait.hpp"
