
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

/**
 * @namespace openassetio_mediacreation::v1::traits::content
 *
 * Trait definitions in the 'content' namespace.
 *
 * Traits related to abstract content.
 */

#include "content/LocatableContentTrait.hpp"
