
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

/**
 * @namespace openassetio_mediacreation::v1::traits::identity
 *
 * Trait definitions in the 'identity' namespace.
 *
 * Traits that aid the identification of an entity.
 */

#include "identity/DisplayNameTrait.hpp"
