
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

/**
 * @namespace openassetio_mediacreation::v1::traits::lifecycle
 *
 * Trait definitions in the 'lifecycle' namespace.
 *
 * Traits that are concerned with describing aspects of the lifecycle of
 * an entity, such as versioning.
 */

#include "lifecycle/StableTrait.hpp"
#include "lifecycle/VersionTrait.hpp"
