
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

/**
 * @namespace openassetio_mediacreation::v1::traits::managementPolicy
 *
 * Trait definitions in the 'managementPolicy' namespace.
 *
 * Traits used in a Manager's managementPolicy response.
 */

#include "managementPolicy/ManagedTrait.hpp"
#include "managementPolicy/ResolvesFutureEntitiesTrait.hpp"
