
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

/**
 * @namespace openassetio_mediacreation::v1::traits::relationship
 *
 * Trait definitions in the 'relationship' namespace.
 *
 * Traits specific to qualities of a relationship.
 */

#include "relationship/SingularTrait.hpp"
#include "relationship/UnboundedTrait.hpp"
