/**
 * Traits defined in the 'openassetio-mediacreation' package.
 */

// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include "auth.hpp"
#include "content.hpp"
#include "identity.hpp"
#include "lifecycle.hpp"
#include "managementPolicy.hpp"
#include "relationship.hpp"
#include "usage.hpp"
