
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

/**
 * @namespace openassetio_mediacreation::v1::traits::usage
 *
 * Trait definitions in the 'usage' namespace.
 *
 * Base traits that scope a trait set for use within a specific context,
 * such as resolution or relationship queries. Exactly one of these
 * should be included in any given Specification.
 */

#include "usage/EntityTrait.hpp"
#include "usage/RelationshipTrait.hpp"
