
// WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

#pragma once

#include <memory>

#include <openassetio/TraitsData.hpp>
#include <openassetio/trait/collection.hpp>

namespace openassetio_abi = openassetio::v1;

#include "../../traits/lifecycle/StableTrait.hpp"
#include "../../traits/lifecycle/VersionTrait.hpp"
#include "../../traits/relationship/UnboundedTrait.hpp"
#include "../../traits/usage/RelationshipTrait.hpp"

namespace openassetio_mediacreation {
inline namespace v1 {
namespace specifications::lifecycle {
/**
 * Retrieves references to alternate stable versions of the same logical
 * entity. This will not include unstable versions such as "latest".
 * Usage: relationship
 */
class StableEntityVersionsRelationshipSpecification {
public:
  inline static const openassetio_abi::trait::TraitSet kTraitSet{
    // 'openassetio-mediacreation:lifecycle.Stable'
    traits::lifecycle::StableTrait::kId,
    // 'openassetio-mediacreation:lifecycle.Version'
    traits::lifecycle::VersionTrait::kId,
    // 'openassetio-mediacreation:relationship.Unbounded'
    traits::relationship::UnboundedTrait::kId,
    // 'openassetio-mediacreation:usage.Relationship'
    traits::usage::RelationshipTrait::kId,
  };

  /**
   * Returns a new instance of the Specification, holding a new
   * TraitsData instance, imbued with the specification's traits.
   */
  static StableEntityVersionsRelationshipSpecification create() {
    return StableEntityVersionsRelationshipSpecification{
      openassetio_abi::TraitsData::make(kTraitSet)};
  }

  /**
   * Constructs the specification as a view on the supplied shared
   * TraitsData instance.
   *
   * @warning Specifications are always a view on the supplied data,
   * which is held by reference. Any changes made to the data will be
   * visible to any other specifications or traits that wrap the same
   * TraitsData instance.
   */
  explicit StableEntityVersionsRelationshipSpecification(openassetio_abi::TraitsDataPtr traitsData)
    : traitsData_{std::move(traitsData)}
  {}

  /**
   * Returns the underlying (shared) TraitsData instance held by this
   * specification.
   */
  [[nodiscard]] const openassetio_abi::TraitsDataPtr& traitsData() const {
    return traitsData_;
  }


  /**
   * Returns the view for the 'openassetio-mediacreation:lifecycle.Stable'
   * trait wrapped around the data held in this instance.
   */
  [[nodiscard]] traits::lifecycle::StableTrait stableTrait() const {
    return traits::lifecycle::StableTrait{traitsData_};
  }

  /**
   * Returns the view for the 'openassetio-mediacreation:lifecycle.Version'
   * trait wrapped around the data held in this instance.
   */
  [[nodiscard]] traits::lifecycle::VersionTrait versionTrait() const {
    return traits::lifecycle::VersionTrait{traitsData_};
  }

  /**
   * Returns the view for the 'openassetio-mediacreation:relationship.Unbounded'
   * trait wrapped around the data held in this instance.
   */
  [[nodiscard]] traits::relationship::UnboundedTrait unboundedTrait() const {
    return traits::relationship::UnboundedTrait{traitsData_};
  }

  /**
   * Returns the view for the 'openassetio-mediacreation:usage.Relationship'
   * trait wrapped around the data held in this instance.
   */
  [[nodiscard]] traits::usage::RelationshipTrait relationshipTrait() const {
    return traits::usage::RelationshipTrait{traitsData_};
  }


private:
  openassetio_abi::TraitsDataPtr traitsData_;
};
}  // namespace specifications::lifecycle
}  // namespace v1
}  // namespace openassetio_mediacreation