// Copyright (c) 2025 The Foundry Visionmongers Ltd.  All Rights Reserved.

#ifndef DDIMAGE_OPSTATE_H
#define DDIMAGE_OPSTATE_H

#include "DDImage/Hash.h"
#include "DDImage/GeneralInfo.h"

#include "fdk/base/Time.h"

#include <vector>
#include <set>
#include <iostream>

class Node;

namespace DD {
  namespace Image {
    class Op;
    class Iop;
    class DeepOnlyOp;
    class ParticleOp;
    class AxisOp;
    class CameraOp;
    class LightOp;
    class SceneOpI;
    class AxisSceneOp;
    class CameraSceneOp;
    class LightSceneOp;
    class GeomOp;
    class GeometryProviderI;


    //! For passing to Op state updating methods and stored in the inputs list of an Op.
    //! This is data flowing down the Op graph which may need to be manipulated by nodes
    //! other than the one that generated the Op, for example FrameHold and TimeOffset.
    struct DDImage_API OpState
    {
      Hash         opHash;                  //!< Hash for the Op's current OutputContext state
      bool         opHashAnimates = false;  //!< Will the OutputContext hash likely vary in time?
      Hash         editVersionHash;         //!< Hash for the Op's 'edit version'
      //
      Hash         topologyHash;            //!< Topology state of the graph, unaffected by knobs
      GeneralInfo  opInfo;                  //!< Info for the Op


      OpState() = default;

      //! Special Op ctor retrieves the graph state stored in \a op.
      explicit OpState(Op* op);

      //! Only compare the states ignoring GeneralInfo contents.
      bool operator==(const OpState& b) const;

      //! Reset to defaults.
      void resetStates();

      //! Append input states to the current ones.
      void append(const OpState& b);

      //! Append to both editVersion and context hashes and animating flag:
      void appendStates(const DD::Image::Hash& hash, bool hashAnimates, const DD::Image::Hash& versionHash);
    };


    //------------------------------------------------------------------------


    //! For capturing the Op graph state at any arbitrary graph point, typically an Op input
    //! or output. It contains a pointer to an Op, the graph state for the Op at this point,
    //! and a Node if one exists in the graph at this point.
    //!
    //! A valid OpGraphContext must have a non-null \a op pointer, while the \a node can be
    //! null. A null \a node will commonly occur when Ops are directly connected together
    //! without participating creator Nodes, or when connecting dangling input to default
    //! Ops (the default Op usually has no owner Node).
    //!
    //! Note that if non-null \a node may not be the same Node that \a op was generated by
    //! since there may be additional non-OpNodes in between \a op's Node and this point
    //! in the graph. When this is the case \a graphState can be different than the one
    //! stored in \a op due to those additional Nodes modifying the graph info. The topology
    //! hash will also show differences in the node graph structure between two points.
    struct DDImage_API OpGraphLocation {
      Op*      op = nullptr;    //!< The Op at this graph point (maybe not created by 'node')
      OpState  graphState;      //!< State of op at this graph point (maybe not same as stored in 'op')
      Node*    node = nullptr;  //!< The Node at this graph point, if it exists (maybe not same as the 'op' node)


      OpGraphLocation() = default;
      //! graphState and node are copied from _op, if valid.
      explicit OpGraphLocation(Op* _op);
      //! If _node is null then it will be copied from _op, if valid.
      OpGraphLocation(Op* _op, const OpState& _state, Node* _node = nullptr);

      //! Returns true when both op and node are valid.
      bool isNodeGraphLocation() const { return (op != nullptr && node != nullptr); }

      //! Returns true if the location has a valid Op but no owner Node.
      //! Commonly occurs when Ops are directly connected together without participating creator
      //! Nodes, or when connecting dangling input to default Ops.
      bool isOrphanedOp() const { return (op != nullptr && node == nullptr); }

      //! Note that a valid OpGraphLocation must have a non-null Op, but can have a null Node.
      explicit operator bool() const { return (op != nullptr); }

      //! Only compares the Op* and its graph state.
      bool operator == (const OpGraphLocation& b) const { return (op == b.op && graphState == b.graphState); }
      bool operator != (const OpGraphLocation& b) const { return !(*this == b); }
      bool operator <  (const OpGraphLocation& b) const;
      bool operator >  (const OpGraphLocation& b) const { return !(*this < b); }

      //---------------------------------------------------------

      //! Hash from graphState. Note - may be different than op->hash()!
      const Hash& opHash() const { return graphState.opHash; }

      //! Does the graphState opHash animate? Note - may be different than op->varyingOutputHash()!
      bool opHashAnimates() const { return graphState.opHashAnimates; }
      bool varyingOutputHash() const { return opHashAnimates(); }

      //! Edit version hash from graphState. Note - may be different than op->editVersionHash()!
      const Hash& editVersionHash() const { return graphState.editVersionHash; }

      //! Hash of input graph structure unaffected by knob values.
      const Hash& topologyHash() const { return graphState.topologyHash; }

      //---------------------------------------------------------

      //! Returns \a node's name if it exists, otherwise \a op's node name if it exists.
      //! Since \a node takes priority over \a op this name will always default to the
      //! location Node which may not be the Op's creator node.
      //!
      //! Note this can be an empty string but will always be non-null.
      const char* nodeName() const;

      //! Same, but makes the node name unique if cloned by appending the clone index so
      //! the string can be used as an identifier.
      //! Since \a node takes priority over \a op this name will always default to the
      //! location Node which may not be the Op's creator node.
      std::string nodeIdentifierName() const;

      //--------------------------------------------------------------
      // Time management conveniences:

      //! If the location contains a Node apply its out->in time remapping function, otherwise
      //! outTimes are just copied to inTimes.
      void applyTimeRemapping(const fdk::TimeValueSet& outTimes, fdk::TimeValueSet& inTimes) const;

      //! Same but with a time list source.
      void applyTimeRemapping(const fdk::TimeValueList& outTimes, fdk::TimeValueSet& inTimes) const;


      //--------------------------------------------------------------
      // Convenience cast op to various Op subclasses, if possible:

      Iop*           iop() const;
      DeepOnlyOp*    deepOnlyOp() const;

      ParticleOp*    particleOp() const;

      AxisOp*        axisOp() const;
      LightOp*       lightOp() const;
      CameraOp*      cameraOp() const;

      SceneOpI*      sceneOpI() const;
      AxisSceneOp*   axisSceneOp() const;
      CameraSceneOp* cameraSceneOp() const;
      LightSceneOp*  lightSceneOp() const;

      GeometryProviderI* geometryProvider() const;
      GeomOp*            geomOp() const;

    };

    using OpGraphLocations = std::vector<OpGraphLocation>;
    using OpGraphLocationSet = std::set<OpGraphLocation>;


    DDImage_API
    std::ostream& operator << (std::ostream&, const OpState&);

    DDImage_API
    std::ostream& operator << (std::ostream&, const OpGraphLocation&);

  }
} // namespace DD::Image

#endif
