// Copyright (c) 2025 The Foundry Visionmongers Ltd. All Rights Reserved.

#ifndef SLR_FILTER_H
#define SLR_FILTER_H

#include "DDImage/Iop.h"
#include "DDImage/Knob.h"
#include "DDImage/Knobs.h"
#include "DDImage/SlrShadingContext.h"
#include "DDImage/SlrEngineContext.h" // convenience for SlrFilter plugins

#include "fdk/base/Time.h"

#include <vector>
#include <unordered_map>

namespace slr
{
  class SlrIntegratorContext;

  //-----------------------------------------------------------------------------


  /*! This class is passed to an SlrSampleFilter from the renderer pixel loop for each pixel
      being rendered.
  */
  class DDImage_API SlrSampleFilterContext
  {
  public:
    //! Integrator context currently in use.
    const SlrIntegratorContext& Itx() const { return _Itx; }

    const fdk::Vec2i&  pixelXY() const;
    int32_t            pixelX() const;
    int32_t            pixelY() const;

    bool  isDebugPixel() const;
    bool  isDebugSample() const;

    //! The list of output sample 'stacks' being filtered, originally generated by the
    //! integrator.
    //! Each stack in the list corresponds to a camera ray and there can be multiple
    //! surface samples along the ray in sorted Z order, thus the term 'stack'.
    StxLayeringStackBundle&  outputSampleStacks();


  protected:
    friend class ThreadContext;
    friend class RenderEngine;
    const SlrIntegratorContext& _Itx;                 //!< Integrator context being used
    StxLayeringStackBundle*     _outputSampleStacks;  //!< Sample stacks

    explicit SlrSampleFilterContext(const SlrIntegratorContext&);
  };


  //-----------------------------------------------------------------------------


  /*! \class slr::SlrFilterOp

      Op base class for ScanlineRender filter nodes.
  */
  class DDImage_API SlrFilterOp : public SlrRenderOp
  {
  public:
    explicit SlrFilterOp(Node*);

    //! Define the material op's shape in the DAG.
    const char*  node_shape() const override;
    //! All material operators default to a orangish color.
    unsigned     node_color() const override;

    bool can_link() const override { return false; }

    //! Allow ScanlineRender2 or SlrFilter connections *only*.
    bool  test_input(int nodeInput, DD::Image::Op* op) const override;

    //!
    void  knobs(DD::Image::Knob_Callback) override;

    void  _validate(bool for_real) override;
    void  _open() override;
    void  _close() override;

    //------------------------------------------------------------
    // From Iop:
    void  _request(int x, int y, int r, int t, DD::Image::ChannelMask outChannels, int count) override;
    void  engine(int y, int x, int r, DD::Image::ChannelMask outChannels, DD::Image::Row& outRow) override;

    //------------------------------------------------------------
    // From DeepOp:
    void  getDeepRequests(DD::Image::Box box, const DD::Image::ChannelSet& outChannels, int count, std::vector<DD::Image::RequestData>& requests) override;
    bool  doDeepEngine(DD::Image::Box box, const DD::Image::ChannelSet& outChannels, DD::Image::DeepOutputPlane& outDeepPlane) override;

    //-------------------------------------------------------------

    //! Return the node input to use for the render scene source.
    int32_t  sceneInput() const override { return 0; }

    //! After _validate() is done this returns the upstream ScanlineRender Op, if
    //! if one is connected to.
    SlrRenderOp*  renderEngineOp() override { return _renderEngineOp; }

    //! After _validate() is done this returns the upstream ScanlineRender Op's
    //! render context, if one is connected to.
    SlrEngineContext*  renderEngineContext() override { return _renderEngineContext; }

    //! Pass to input.
    void renderEngineRequestSetup() override;

    //-------------------------------------------------------------

    //! Allocate an SlrSampleFilter and add it to the list to be executed. The order
    //! of execution is first to last, so usually the new filter is appended to the
    //! end of the list.
    //! Default implementation passes the filter list to input0.
    virtual void  buildSampleFilterList(SlrFilterOpList& filters);

    //! Filter implementation called by the render engine after the integrator has
    //! generated the output surface samples.
    //!
    //! Must implement.
    virtual void  filter(SlrSampleFilterContext&       Ftx,
                         const DD::Image::ChannelPack& getChannels,
                         const DD::Image::ChannelPack& getColorChannels,
                         const DD::Image::ChannelPack& getDataChannels) const = 0;


  protected:
    SlrRenderOp*      _renderEngineOp;
    SlrEngineContext* _renderEngineContext;
    SlrFilterOpList   _filters;

  };

  using SlrFilterOpList = std::vector<SlrFilterOp*>;


} // namespace slr

#endif
