// Copyright (c) 2025 The Foundry Visionmongers Ltd.  All Rights Reserved.

#ifndef SLR_RAYCONTEXT_H
#define SLR_RAYCONTEXT_H

#include "ndk/geo/render/RayContext.h"

#include "DDImage/DDImage_API.h"

namespace slr
{
  class SlrThreadContext;
  class SlrShadingContext;
  class SlrIntegratorContext;
  class StxBundle;
  class StxLayeringStack;
  struct SampleInfo;

  //! Predefined undefined/error/invalid SlrRayContext returned by ray retrieval
  //! methods to identify an error condition such as an out of range ray request.
  DDImage_API const struct SlrRayContext&  InvalidRay();

  //-----------------------------------------------------------------------------


  //! \struct SlrRayContext
  //!
  //! Specialization of ndk::RayContext for Slr2 use, with a reference to the thread
  //! context data.
  //!
  //! While the ray geometry is free to be manipulated the intersection data
  //! generated by this ray is stored in thread-safe memory managed by the
  //! renderer.
  struct DDImage_API SlrRayContext : public ndk::RayContext
  {
    //! Returns true if this ray is attached to a render thread context.
    //! InvalidRay() will return false.
    bool  isValid() const;

    //! Access the writable RayContext portion of this.
    ndk::RayContext&        asRayContext() { return *this; }
    const ndk::RayContext&  asRayContext() const { return *const_cast<SlrRayContext*>(this); }

    //! Source surface if this ray was spawned from one, or null if not.
    SlrShadingContext*  srcStx() const;

    //! Retrieve the hit point count from the last ray cast, and is only valid
    //! until the next ray cast call this ray is passed to.
    int32_t  nHitPoints() const;

    //! Sort the hits in desired direction. Ray hit index 0 is either nearest or farthest after sorting.
    void  sortHits(bool nearToFar = true) const;

    //! Ray hit index 0 is nearest after sorting.
    void  sortHitsNearToFar() const { sortHits(true); }

    //! Ray hit index 0 is farthest after sorting.
    void  sortHitsFarToNear() const { sortHits(false); }

    //! Retrieve the list of hits filled in during the last ray cast call this
    //! ray context was passed to. The list of hits are always along the ray's
    //! direction vector which is why this list is termed a 'stack'.
    //!
    //! Note that this list is volatile and will be overwritten during the next
    //! ray cast call this ray is passed to, so move any hit points you care
    //! about out of the list before passing this ray to another intersection
    //! method.
    StxLayeringStack&  hitPointStack() const;

    //------------------------------------------

    //! Retrieve a hit point from the last ray cast from 0..nRayHitPoints(). No range checking
    //! or null testing is done - the index is assumed to be within nRayHitPoints().
    const ndk::RayHitPointf&  getHitPoint(int32_t rayHitIndex = 0) const;

    //! Move/extract the hit point reference out of this ray's hit stack, transferring ownership
    //! of it to \a toBundle and setting the old reference to null.
    //! Note this does -NOT- change the size of the hit point list, for performance reasons.
    //! Returns a reference to the hit point in the new location.
    const ndk::RayHitPointf&  moveHitPointTo(int32_t rayHitIndex, StxBundle& toBundle) const;

    //! Same, but to the layering stack bundle.
    const ndk::RayHitPointf&  moveHitPointToLayeringStack(int32_t rayHitIndex) const;

    //------------------------------------------

    //! OpacityTraitsMask of all the hit points OR'd together.
    ndk::OpacityTraitsMask  hitPointsOpacityOrMask() const;

    //! OpacityTraitsMask of all the hit points AND'd together.
    ndk::OpacityTraitsMask  hitPointsOpacityAndMask() const;

    //! All hits are opaque-solid, that is we cannot see through the first surface and if
    //! desired can skip all the other hits.
    bool  areAllHitsOpaqueSolid() const;

    //! If false then only the first hit matters since we should never see through it. If true
    //! then all the hits need to be blended, and if doAllHitsBlendToOpaque() is also true then
    //! blending can be done front-to-back.
    bool  doAllHitsBlend() const;
    //! If true all the hits do 'standard' blending that can result in 1.0 opacity. If false
    //! then at least one of the hits needs to do 'non-standard' blending (like min, max, plus)
    //! and blending should be done back-to-front.
    bool  doAllHitsBlendToOpaque() const;


    //-------------------------------------------------------------------------

    //! Retrieve the list of shading contexts 
    StxLayeringStack&  layeringStack() const;

    //! Empty the layering stack.
    void  clearLayeringStack() const;


    //-------------------------------------------------------------------------

    //! For internal use only (for constructing error rays.)
    explicit SlrRayContext(int16_t i) : ndk::RayContext(i) {}

    friend DDImage_API std::ostream& operator << (std::ostream& o, const SlrRayContext&);

  protected:
    //! Member vars left intentionally uninitialized for performance reasons.
    SlrRayContext() = default;
    explicit SlrRayContext(const ndk::RayContext& rtx) : ndk::RayContext(rtx) {}
    SlrRayContext(const fdk::Vec3f& _origin,
                  const fdk::Vec3f& _dir,
                  TypeMask          _type,
                  fdk::TimeValue    _time,
                  int16_t           _id,
                  float             _minDist,
                  float             _maxDist) : ndk::RayContext(_origin, _dir, _type, _time, _id, _minDist, _maxDist) {}
  };


  //-----------------------------------------------------------------------------


  //! \struct SlrRayContext
  //!
  //! Specialization of SlrRayContext for single ray trace (ad-hoc rays)
  //! which are not persistent. Wraps a single SlrRayContext which is released
  //! on destruction.
  struct DDImage_API SlrAdHocRay
  {
    //! Attaches temp ray data until destruction, uses shading context for thread context
    //! and ray continuance info.
    //! Building an ad-hoc ray requires important information like ray depth, sample info,
    //! etc from the rendering environment.
    explicit SlrAdHocRay(const SlrShadingContext& srcStx);
    //! Same but copies source ray.
    SlrAdHocRay(const SlrShadingContext& srcStx, const ndk::RayContext& rtx);
    //! Same but with parameter construction.
    SlrAdHocRay(const SlrShadingContext& srcStx,
                const fdk::Vec3f&        origin,
                const fdk::Vec3f&        dir,
                SlrRayContext::TypeMask  type,
                fdk::TimeValue           time,
                int16_t                  id,
                float                    minDist,
                float                    maxDist);

    //! Attaches temp ray data until destruction, uses another ray for thread context
    //! and ray continuance info, and copies \a srcRtx's geometry.
    //! Building an ad-hoc ray requires important information like ray depth, sample info,
    //! etc from the rendering environment.
    explicit SlrAdHocRay(const SlrRayContext& srcRtx);

    //----------------------------------------
    // Wrapped ray access

    //! Return the wrapped ray. 
    SlrRayContext&        ray();
    const SlrRayContext&  ray() const;

    //! Cast to wrapped ray.
    operator SlrRayContext& () { return ray(); }

    //----------------------------------------
    // Convenience accessors

    const fdk::Vec3f&  origin() const;
    const fdk::Vec3f&  direction() const;
    float              minT() const;
    float              maxT() const;
    fdk::Vec3f         directionDx() const;
    fdk::Vec3f         directionDy() const;
    //
    fdk::TimeValue             time() const;
    SlrRayContext::TypeMask    typeMask() const;
    SlrRayContext::OriginMask  originMask() const;
    int16_t                    id() const;

    void set(const fdk::Vec3f&       origin,
             const fdk::Vec3f&       dir,
             SlrRayContext::TypeMask type,
             fdk::TimeValue          time,
             int16_t                 id,
             float                   minDist,
             float                   maxDist);

    void setGeometry(const fdk::Vec3f& origin,
                     const fdk::Vec3f& dir,
                     float             minDist,
                     float             maxDist);

    //----------------------------------------

    //! Releases temp ray data.
    ~SlrAdHocRay();

    friend DDImage_API std::ostream& operator << (std::ostream& o, const SlrAdHocRay&);

  private:
    struct RayData* _data;
  };


  //-----------------------------------------------------------------------------


  class DDImage_API SlrRayBundle
  {
  public:
    using ListT = std::vector<struct RayData*>;

    //! Default ctor makes an invalid, empty bundle.
    SlrRayBundle();

    //! Releases all the rays in the list.
    ~SlrRayBundle();

    //! Is the bundle bound to valid data?
    bool     isValid() const { return (_sttx != nullptr); }

    //! Returns true is bundle is not empty.
    explicit operator bool() const { return (!empty() && _sttx); }

    int32_t  size() const { return _list.size(); }
    bool     empty() const { return _list.empty(); }

    SlrRayContext&        operator [] (int i);
    const SlrRayContext&  operator [] (int i) const;

    SlrRayContext&    ray(int i) { return (*this)[i]; }
    ndk::RayContext&  rayContext(int i) { return (*this)[i].asRayContext(); }

    SlrRayContext**        array();
    const SlrRayContext**  array() const;

    //! Empties the list and releases the ray data.
    void  clear();

    //----------------------------------------------------------

    //! Type shared by all rays in bundle (camera, glossy, etc).
    SlrRayContext::TypeMask  rayType() const { return _type; }

    //! Add another RayContext to the bundle, returning a reference to it and incrementing
    //! the current bundle count. This method assumes this bundle currently 'owns' the
    //! RayContextList by a single thread and is always appending to the end of the list.
    //!
    //! Note this DOES NOT make the added ray the active one or this bundle the active bundle,
    //! use \a selectActiveRay() for that.
//    SlrRayContext&  addRay(const ndk::RayContext& rtx) const; // copy
//    SlrRayContext&  addRay(ndk::RayContext&& rtx) const; // move

    //----------------------------------------------------------

    //! Iterator support
    struct DDImage_API iterator
    {
      explicit iterator(ListT::iterator it) noexcept : _it(it) {}

      SlrRayContext&  operator *() noexcept;
      bool operator == (const iterator& b) const noexcept { return (_it == b._it); }
      bool operator != (const iterator& b) const noexcept { return (_it != b._it); }
      iterator& operator++() noexcept { ++_it; return *this; }

      explicit operator void*() noexcept { return &(*_it); } // for debugging

      iterator(const iterator&) = delete;
      void operator=(const iterator&) = delete;

    private:
      ListT::iterator _it;
    };

    using const_iterator = iterator;

    iterator        begin();
    const_iterator  begin() const;
    iterator        end();
    const_iterator  end() const;

    //----------------------------------------------------------

    friend DDImage_API std::ostream& operator << (std::ostream& o, const SlrRayBundle& b);

  private:
    friend class ThreadContext;
    friend class RenderEngine;
    class ThreadContext*    _sttx;
    ListT                   _list;
    SlrRayContext::TypeMask _type;  //!< Type shared by all rays in bundle (camera, glossy, etc)

    SlrRayBundle(ThreadContext*, SlrRayContext::TypeMask type);
    SlrRayBundle(const SlrRayBundle&) = delete;
    void operator=(const SlrRayBundle&) = delete;
  };


} // namespace slr


#endif
